apiVersion: v1
kind: Service
metadata:
  name: vpnhub
  namespace: vpnhub
  labels:
    app.kubernetes.io/name: vpnhub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vpnhub
  ports:
    - name: http
      port: 80
      targetPort: http   # → containerPort 8000
