blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/AlexeyShalaev/vpn-hub/discussions
    about: Ask a question or start a discussion about vpn-hub
