"""initial schema

Revision ID: ae99804150d1
Revises:
Create Date: 2026-07-03 00:11:00.144044
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ae99804150d1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("devices_pkey")),
    )
    op.create_index(op.f("devices_user_id_idx"), "devices", ["user_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("groups_pkey")),
        sa.UniqueConstraint("token", name=op.f("groups_token_key")),
    )
    op.create_index(op.f("groups_owner_user_id_idx"), "groups", ["owner_user_id"], unique=False)
    op.create_table(
        "pools",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pools_pkey")),
    )
    op.create_index(op.f("pools_owner_user_id_idx"), "pools", ["owner_user_id"], unique=False)
    op.create_table(
        "servers",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("ssh_user", sa.String(length=64), nullable=False),
        sa.Column("ssh_port", sa.String(length=8), nullable=False),
        sa.Column("ssh_auth", sa.String(length=16), nullable=False),
        sa.Column("ssh_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("last_check_at", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("servers_pkey")),
    )
    op.create_index(op.f("servers_owner_user_id_idx"), "servers", ["owner_user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("subject_kind", sa.String(length=8), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
    )
    op.create_index(op.f("sessions_subject_id_idx"), "sessions", ["subject_id"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("settings_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_phone_idx"), "users", ["phone"], unique=True)
    op.create_table(
        "admins",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("admins_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("admins_pkey")),
    )
    op.create_table(
        "device_configs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("device_id", sa.String(length=32), nullable=False),
        sa.Column("server_id", sa.String(length=32), nullable=False),
        sa.Column("vpn_type", sa.String(length=16), nullable=False),
        sa.Column("proto", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("client_public_key", sa.String(length=64), nullable=True),
        sa.Column("client_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("client_name", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("device_configs_device_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("device_configs_pkey")),
    )
    op.create_index(op.f("device_configs_device_id_idx"), "device_configs", ["device_id"], unique=False)
    op.create_table(
        "group_members",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("group_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("group_members_group_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("group_members_pkey")),
    )
    op.create_index(op.f("group_members_group_id_idx"), "group_members", ["group_id"], unique=False)
    op.create_index(op.f("group_members_user_id_idx"), "group_members", ["user_id"], unique=False)
    op.create_table(
        "group_pool_access",
        sa.Column("group_id", sa.String(length=32), nullable=False),
        sa.Column("pool_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("group_pool_access_group_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["pools.id"], name=op.f("group_pool_access_pool_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "pool_id", name=op.f("group_pool_access_pkey")),
    )
    op.create_table(
        "group_server_access",
        sa.Column("group_id", sa.String(length=32), nullable=False),
        sa.Column("server_id", sa.String(length=32), nullable=False),
        sa.Column("vpn_type", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("group_server_access_group_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], name=op.f("group_server_access_server_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "server_id", "vpn_type", name=op.f("group_server_access_pkey")),
    )
    op.create_table(
        "pool_servers",
        sa.Column("pool_id", sa.String(length=32), nullable=False),
        sa.Column("server_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["pool_id"], ["pools.id"], name=op.f("pool_servers_pool_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], name=op.f("pool_servers_server_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pool_id", "server_id", name=op.f("pool_servers_pkey")),
    )
    op.create_table(
        "server_protocols",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("server_id", sa.String(length=32), nullable=False),
        sa.Column("vendor", sa.String(length=16), nullable=False),
        sa.Column("proto", sa.String(length=24), nullable=False),
        sa.Column("container", sa.String(length=64), nullable=False),
        sa.Column("port", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("installed", sa.Boolean(), nullable=False),
        sa.Column("running", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("external_clients", sa.Integer(), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("material_encrypted", sa.Text(), nullable=True),
        sa.Column("pending_revoke_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], name=op.f("server_protocols_server_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("server_protocols_pkey")),
        sa.UniqueConstraint("server_id", "proto", name="server_protocols_uq"),
    )
    op.create_index(op.f("server_protocols_server_id_idx"), "server_protocols", ["server_id"], unique=False)
    op.create_table(
        "server_vpns",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("server_id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("installed", sa.Boolean(), nullable=False),
        sa.Column("running", sa.Boolean(), nullable=False),
        sa.Column("port", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], name=op.f("server_vpns_server_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("server_vpns_pkey")),
        sa.UniqueConstraint("server_id", "type", name="server_vpns_uq"),
    )
    op.create_index(op.f("server_vpns_server_id_idx"), "server_vpns", ["server_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("server_vpns_server_id_idx"), table_name="server_vpns")
    op.drop_table("server_vpns")
    op.drop_index(op.f("server_protocols_server_id_idx"), table_name="server_protocols")
    op.drop_table("server_protocols")
    op.drop_table("pool_servers")
    op.drop_table("group_server_access")
    op.drop_table("group_pool_access")
    op.drop_index(op.f("group_members_user_id_idx"), table_name="group_members")
    op.drop_index(op.f("group_members_group_id_idx"), table_name="group_members")
    op.drop_table("group_members")
    op.drop_index(op.f("device_configs_device_id_idx"), table_name="device_configs")
    op.drop_table("device_configs")
    op.drop_table("admins")
    op.drop_index(op.f("users_phone_idx"), table_name="users")
    op.drop_table("users")
    op.drop_table("settings")
    op.drop_index(op.f("sessions_subject_id_idx"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("servers_owner_user_id_idx"), table_name="servers")
    op.drop_table("servers")
    op.drop_index(op.f("pools_owner_user_id_idx"), table_name="pools")
    op.drop_table("pools")
    op.drop_index(op.f("groups_owner_user_id_idx"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("devices_user_id_idx"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
